from enum import Enum


class EmployeeTeam(str, Enum):

    ADMINISTRATION = "TEAM_ADMINISTRATION"

    CONCIERGE_SERVICE = "TEAM_CONCIERGE"

    TECHNICAL = "TEAM_TECH"

    CLEANING = "TEAM_CLEANING"

    SECURITY = "TEAM_SECURITY"
